#ifndef PANDOHAMMER_REGISTER_H
#define PANDOHAMMER_REGISTER_H

#define MCSR_SLEEP     0x7A5
#define MCSR_L1SPBASE  0x7A6

#define MCSR_MCOREID    0xF15
#define MCSR_MPODID     0xF16
#define MCSR_MPXNID     0xF17
#define MCSR_MCOREHARTS 0xF18
#define MCSR_MPODCORESX 0xF19
#define MCSR_MPXNPODS   0xF1A
#define MCSR_MNUMPXN    0xF1B
#define MCSR_MCOREL1SPSIZE 0xF1C
#define MCSR_MPODL2SPSIZE  0xF1D
#define MCSR_MPXNDRAMSIZE  0xF1E
#define MCSR_MPODCORESY 0xF1F

#endif
