# SPDX-License-Identifier: MIT
# Copyright (c) 2023 University of Washington

define gdrive
$(eval $1-url = $2)
$(eval get-from-gdrive += $1.mtx)
endef

define uflorida
$(eval $1-url = $2)
$(eval get-from-uflorida += $1.mtx)
endef

###################################################
# list of mtx files to download from google drive #
###################################################
get-from-gdrive :=
$(call gdrive,g7k1,https://drive.google.com/file/d/1vFrohxOijg-HjckN0PTN22KGXlVJTtis/view?usp=sharing)
$(call gdrive,g10k4,https://drive.google.com/file/d/1t-QMhPac5yZM324OT7Wk8G6VeNXmjdt1/view?usp=sharing)
$(call gdrive,g10k8,https://drive.google.com/file/d/1iu3uKe-QGHLgHt-PbYfKxQtDjaFidVZk/view?usp=sharing)
$(call gdrive,g10k16,https://drive.google.com/file/d/1vJneSHOgOMJKUp7lGaC7HN4j9Jf5Rb7c/view?usp=sharing)
$(call gdrive,g11k4,https://drive.google.com/file/d/1tX-QEgqWz-IqrBOgwcu7x5NPvROpgc-j/view?usp=sharing)
$(call gdrive,g11k8,https://drive.google.com/file/d/1FhtDkJ943P6QwshpFJMqWrGy-IEE1_y0/view?usp=sharing)
$(call gdrive,g11k16,https://drive.google.com/file/d/1EPA2sdza01fONMSHH4gz_qdDK3Rcvd5N/view?usp=sharing)
$(call gdrive,g12k4,https://drive.google.com/file/d/1dMMrLfB_9tk2QmgE2yZ2F5J7nqXfDZnh/view?usp=sharing)
$(call gdrive,g12k8,https://drive.google.com/file/d/1sczqgqkvjh2qUObF2dhFqafPPxz1LXAo/view?usp=sharing)
$(call gdrive,g12k16,https://drive.google.com/file/d/1to1OhCByOj3j5mvl0OfrSeKz6pbMvox0/view?usp=sharing)
$(call gdrive,g13k4,https://drive.google.com/file/d/1PgB-IF9CIVQmq6patFpAV2gweAkhWoDr/view?usp=sharing)
$(call gdrive,g13k8,https://drive.google.com/file/d/1QyE4LetPsowCeTW688Gb2_cOkzjUidvr/view?usp=sharing)
$(call gdrive,g13k16,https://drive.google.com/file/d/160NydYn6fN4Q_1pncoGbo70TyxPQcJiI/view?usp=sharing)
$(call gdrive,g14k4,https://drive.google.com/file/d/16n5BmpfWUpgmqvulQL7Lkc3Ru3vFYYz3/view?usp=sharing)
$(call gdrive,g14k8,https://drive.google.com/file/d/1tGvbekT9dDPSCG1hXHhikJ7SF6OSrYRQ/view?usp=sharing)
$(call gdrive,g14k16,https://drive.google.com/file/d/1SzWvjAEOA9yZajLIgoYekc_Wmx4wU2r3/view?usp=sharing)
$(call gdrive,g15k4,https://drive.google.com/file/d/1hNI8d30XTnr8iLjCOH-geqF5j57d4ADH/view?usp=sharing)
$(call gdrive,g15k8,https://drive.google.com/file/d/1QozQNRXnbp7yE2I7qwnUa1IZnwk1DP9X/view?usp=sharing)
$(call gdrive,g15k16,https://drive.google.com/file/d/1BuB5zRusuEkNdH2kotAJahmZn5zVm0n2/view?usp=sharing)
$(call gdrive,g16k4,https://drive.google.com/file/d/1GvGvwAvwjUQoPhhvwi7w-uXie3I6tN-f/view?usp=sharing)
$(call gdrive,g16k8,https://drive.google.com/file/d/1ltwr0zw2P2qRy6iURS30CNBYFhR6ZYuO/view?usp=sharing)
$(call gdrive,g16k16,https://drive.google.com/file/d/1RhNjC2m_m2OEExF7j2BN0YhHJZfJ3U9W/view?usp=sharing)
$(call gdrive,u7k1,https://drive.google.com/file/d/1hefg63DFUdCSs-dE8vOgX-0komVS_nXS/view?usp=sharing)
$(call gdrive,u10k4,https://drive.google.com/file/d/157DSyx7B3xAO7KmdzanOlA3XFLaC5uUT/view?usp=sharing)
$(call gdrive,u10k8,https://drive.google.com/file/d/127ZnCdQg4xmgJtrck9uzj5xmQcwDJNx6/view?usp=sharing)
$(call gdrive,u10k16,https://drive.google.com/file/d/1n7Asre8ZOLh8fyMT4tBU1YAHS1ftMHV0/view?usp=sharing)
$(call gdrive,u11k4,https://drive.google.com/file/d/1z6wsJyWdG-73maMB5NK7Ui2GFd0yMjA1/view?usp=sharing)
$(call gdrive,u11k8,https://drive.google.com/file/d/18DH84AsoiGQSYMOOXlwJnHlraNqr3Xh6/view?usp=sharing)
$(call gdrive,u11k16,https://drive.google.com/file/d/1MJSeSq76wjn-0qlIZ3zLVPBipidYQxmg/view?usp=sharing)
$(call gdrive,u12k4,https://drive.google.com/file/d/1wWd42ZjZEsbyknE7LrC375unaW28LeHk/view?usp=sharing)
$(call gdrive,u12k8,https://drive.google.com/file/d/1KrbN3aZ5VVoec8GxbJDLb3DuZdekbAyI/view?usp=sharing)
$(call gdrive,u12k16,https://drive.google.com/file/d/1CL80dYKZWgu6iZNh0MtQIHyTjclxoyvK/view?usp=sharing)
$(call gdrive,u13k4,https://drive.google.com/file/d/1lEuw7QISf7Tu6rVN874sPsHMLPL8zcX2/view?usp=sharing)
$(call gdrive,u13k8,https://drive.google.com/file/d/1FmyMxsUXEdhUxuwfe3hopXLWG2Q5sbJf/view?usp=sharing)
$(call gdrive,u13k16,https://drive.google.com/file/d/16H_Wu7j5h7GjkUAtqDbaZtS0UvHcm2Hk/view?usp=sharing)
$(call gdrive,u14k4,https://drive.google.com/file/d/1eatkh1kliuZ2X7iYZy96wZWzSKULosUr/view?usp=sharing)
$(call gdrive,u14k8,https://drive.google.com/file/d/1Obq8cGjluHTLSCRMLmJZeUXUIHbVs0-P/view?usp=sharing)
$(call gdrive,u14k16,https://drive.google.com/file/d/1tBCc-7elOiA7GdkO59hif_1Qn9XsechV/view?usp=sharing)
$(call gdrive,u15k4,https://drive.google.com/file/d/1O_KyXAGtPShZZ3WLQOJKHHotP8DU16oZ/view?usp=sharing)
$(call gdrive,u15k8,https://drive.google.com/file/d/1pBh2kZGtQbnyWYx0N_k4flrbhiXXukv7/view?usp=sharing)
$(call gdrive,u15k16,https://drive.google.com/file/d/1ELhY4E_GPSKA-oO_q3F9csO0gBhbjoDN/view?usp=sharing)
$(call gdrive,u16k4,https://drive.google.com/file/d/1FuUmAzUedWF4w8CTT4dA3PorzQdNsp4q/view?usp=sharing)
$(call gdrive,u16k8,https://drive.google.com/file/d/1BFoWWPy_HR8KuZdWi9SqaxqF7C7blyrq/view?usp=sharing)
$(call gdrive,u16k16,https://drive.google.com/file/d/10klumtpAqpSRJD43tc3eDivyTw9SlAdm/view?usp=share_link)

.PHONY: gdrive
gdrive: $(get-from-gdrive)
$(get-from-gdrive): %.mtx:
	$(eval tarfile=$@.tar.gz)
	$(eval tarurl=$($*-url))
	gdown --fuzzy $(tarurl)
	tar zxf $(tarfile)
	rm -f $(tarfile)

all: $(get-from-gdrive)

#######################################################
# list of mtx files to download from Univ. of Florida #
#######################################################
get-from-uflorida :=
# misc
$(call uflorida,bcsstk15,https://suitesparse-collection-website.herokuapp.com/MM/HB/bcsstk15.tar.gz)
$(call uflorida,offshore,https://suitesparse-collection-website.herokuapp.com/MM/Um/offshore.tar.gz)
# networks
$(call uflorida,wiki-Vote,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-Vote.tar.gz)
$(call uflorida,email-Enron,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/email-Enron.tar.gz)
$(call uflorida,web-NotreDame,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-NotreDame.tar.gz)
$(call uflorida,web-Stanford,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-Stanford.tar.gz)
$(call uflorida,web-Google,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-Google.tar.gz)
$(call uflorida,web-BerkStan,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/web-BerkStan.tar.gz)
# roads
$(call uflorida,minnesota,https://suitesparse-collection-website.herokuapp.com/MM/Gleich/minnesota.tar.gz)
$(call uflorida,roadNet-CA,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-CA.tar.gz)
$(call uflorida,roadNet-PA,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-PA.tar.gz)
$(call uflorida,roadNet-TX,https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-TX.tar.gz)
$(call uflorida,road_central,https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/road_central.tar.gz)
$(call uflorida,road_usa,https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/road_usa.tar.gz)
$(call uflorida,europe_osm,https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/europe_osm.tar.gz)

.PHONY: uflorida
uflorida: $(get-from-uflorida)
$(get-from-uflorida): %.mtx:
	$(eval tarurl=$($*-url))
	$(eval tarfile=$*.tar.gz)
	wget $(tarurl)
	tar zxf $(tarfile)
	ln -s $*/$@ $@
	rm -f $(tarfile)

all: $(get-from-uflorida)

##################################
# cleanup downloaded input files #
##################################
clean:
	rm -rf */ *.mtx *.tar.gz
